### ISSUE TITLE
org.owasp.dependencycheck.data.update.exception.UpdateException: The execution of the download was interrupted

### ISSUE THREAD

**Issue by gwsu2008** [dependency-check/DependencyCheck#3320] opened 2021-04-22 18:35 UTC
**Describe the bug**
Jenkins build step invoke step DependencyCheck failed with Caused by: java.lang.NullPointerException: null 
See log file

**Version of dependency-check used**
Jenkins 2.263.3
OWASP Dependency-Check Plugin 5.1.1
Dependency-Check installation: 5.3.2 Dependency Checker

**Log file**
https://gist.github.com/gwsu2008/e6a7eb70f0a74b051c154a36add58850

**To Reproduce**
1. Create a MultiJob Project in Jenkins and add a build step to invoke DependencyCheck
2. Click build

**Arguments for Dependency-Check**
--enableExperimental --format XML --format HTML --prettyPrint

**Expected behavior**
Dependency-Check should not throw java.lang.NullPointerException

**Comment by pwagland** [comment] 2021-04-22 19:06
Most likely a duplicate of #3307, along with almost all of the issues between #3308 to #3318.

**Comment by melloware** [comment] 2021-04-22 19:48
+1000000

**Comment by jeremylong** [comment] 2021-04-23 12:54
This was resolved when the NVD corrected the data feeds.

**Closed as completed by jeremylong** 2021-04-23 12:54 UTC
Labels: bug
