### ISSUE TITLE
Remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by aspoddar** [dependency-check/DependencyCheck#2844] opened 2020-09-29 09:54 UTC
Hi Team,

We are using OWASP Dependency Check  tool in our Azure Devops pipelines , Since yesterday we are facing “403” error for all our pipelines .i.e our pipelines are not able to connect and download OWASP dependency check tool and even I manually accessing the web url but I am getting forbidden error. Please can you help us to overcome this error.

For your reference here are the below screenshot .

##[debug]INPUT_FORMAT: 'HTML,JSON,JUNIT'
##[debug]INPUT_FAILONCVSS (empty)
##[debug] Defaulted to: ''
##[debug]INPUT_SUPPRESSIONPATH: 'D:\a\1\s\ui\suppressions.xml'
##[debug]INPUT_ENABLEEXPERIMENTAL: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_ENABLERETIRED: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_ENABLEVERBOSE: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_DATAMIRRORJSON (empty)
##[debug] Defaulted to: ''
##[debug]INPUT_DATAMIRRORODC (empty)
##[debug] Defaulted to: ''
##[debug]INPUT_ADDITIONALARGUMENTS (empty)
##[debug] Defaulted to: ''
Creating dependency check test results directory at D:\a\1\TestResults\dependency-check

    Directory: D:\a\1\TestResults

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        9/28/2020   2:46 PM                dependency-check                                                      
Downloading Dependency Check installer...
##[debug]GET https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2-release.zip with 0-byte payload
##[debug]STDERR: The remote server returned an error: (403) Forbidden.
##[error]System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[debug]Processed: ##vso[task.logissue type=error]System.Net.WebException: The remote server returned an error: (403) Forbidden.%0D%0A   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)%0D%0A   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[debug]Processed: ##vso[task.complete result=Failed]Unhandled error condition detected.
##[debug]Leaving D:\a\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\5.3.2003\dependency-check-build-task.ps1.
Ending Dependency Check...

Finishing: Dependency Check

**Comment by mprins** [comment] 2020-09-29 10:26
duplicate of #2843

**Closed as completed** 2020-09-29 10:54 UTC
Labels: duplicate, question

**Comment by TalZiv** [comment] 2020-09-29 12:09
Hi,

If you encounter this issue In jenkins you can look at my fix at the Jenkins Jira [Here](https://issues.jenkins-ci.org/browse/JENKINS-63806?focusedCommentId=398382&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-398382)

**Comment by aspoddar** [comment] 2020-09-29 12:17
No i facing this issue in azure pipeline , Please can someone help me here..

**Comment by TalZiv** [comment] 2020-09-29 12:25
Have a look at this https://github.com/dependency-check/azuredevops/issues/47
