### ISSUE TITLE
False Positive on micronaut-xxx-netty

### ISSUE THREAD

**Issue by Mura-Mi** [dependency-check/DependencyCheck#4010] opened 2022-01-21 02:47 UTC
False positive on library micronaut-http-netty-3.1.3.jar - reported as `cpe:2.3:a:netty:netty:3.1.3:*:*:*:*:*:*:*`
```groovy
implementation 'io.micronaut:micronaut-http-netty:3.1.3'
```

Same false -positive occurs with `micronaut-buffer-netty-3.1.3.jar` and `micronaut-http-server-netty-3.1.3.jar`

micronaut-http-netty relies on netty 4.1.69.Final, which is over 4.1.44.
micronaut-http-netty module uses micronaut's semantic versioning, not netty versioning.
Perhaps #3975 has same cause.

We can suppress this with our local suppress configuration, but some improvement is possible in DependencyCheck?

We're using `{ module = "org.owasp:dependency-check-gradle", version = "6.5.3" }`

**Comment by aikebah** [comment] 2022-05-12 19:34
@Mura-Mi still the case for 7.1.0? Or was this already resolved, but unnoticed by our FP suppressions in the 7.x series?

**Comment by aikebah** [comment] 2022-05-12 19:34
Could not reproduce with same dependency in Maven plugin (don't have a gradle environment at hand right now)

**Comment by aikebah** [comment] 2022-05-14 14:58
Fixed by 02bb5da21ec71dbd6159712ac9416194d7bc2c57 which went into 7.1.0

**Closed as completed by aikebah** 2022-05-14 14:58 UTC
Labels: FP Report
