### ISSUE TITLE
[FP]: swagger-parser-safe-url-resolver flagged for parse-url_project

### ISSUE THREAD

**Issue by nhumblot** [dependency-check/DependencyCheck#6441] opened 2024-02-05 06:08 UTC
### Package URl

pkg:maven/io.swagger.parser.v3/swagger-parser-safe-url-resolver@2.1.20

### CPE

cpe:2.3:a:parse-url_project::::::::*

### ODC Integration

None

### ODC Version

9.0.9

### Description

This FP has already been declared in #5754 but the suppression rule got limited to the version 2.1.14, which raises an alert again when using another one as a dependency.

**Comment by aggeboe** [comment] 2024-02-05 07:37
Possible duplicate of https://github.com/jeremylong/DependencyCheck/issues/6422

**Closed as completed** 2024-02-05 11:21 UTC
Labels: FP Report, maven

**Comment by nhumblot** [comment] 2024-02-05 16:19
> Possible duplicate of https://github.com/jeremylong/DependencyCheck/issues/6422

Sorry, I didn't see your ticket 😦
