### ISSUE TITLE
False Positive on activemq-client

### ISSUE THREAD

**Issue by igmar** [dependency-check/DependencyCheck#2345] opened 2019-11-25 11:16 UTC
False positive on library activemq-client-5.15.10.jar reported as
```
cpe:/a:apache:activemq:5.15.10
```
```
<dependency>
    <groupId>org.activemq.activemq</groupId>
    <artifactId>activemq-client</artifactId>
    <version>5.15.10</version>
</dependency>
```
This version is not effected by any CVE's in the CPE.

This dependency is related to Prometheus, but does not follow the same version numbering.

**Comment by chadlwilson** [comment] 2019-11-30 05:07
Looks like a dupe of #2334?

**Closed as completed** 2019-12-29 12:59 UTC
Labels: duplicate, FP Report
