### ISSUE TITLE
Apparent syntax error in dependency-check.sh line 127 in release 5.2.3

### ISSUE THREAD

**Issue by gemzdude** [dependency-check/DependencyCheck#2322] opened 2019-11-11 22:57 UTC
Executing dependency-check.sh in release 5.2.3 results in bash syntax error on line 127.

It appears to be a missing $

**Comment by jeremylong** [comment] 2019-11-12 10:33
duplicate of #2317.  5.2.4 is being pushed shortly.

**Closed as completed by jeremylong** 2019-11-12 10:33 UTC
Labels: bug, duplicate
