### ISSUE TITLE
[FP]: aws-java-sdk-sagemakerfeaturestoreruntime-1.12.263

### ISSUE THREAD

**Issue by dampcake** [dependency-check/DependencyCheck#4682] opened 2022-07-19 17:32 UTC
### Package URl

pkg:maven/com.amazonaws/aws-java-sdk-sagemakerfeaturestoreruntime@1.12.263

### CPE

`cpe:2.3:a:sage:sage:1.12.263:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.1.1

**Comment by aikebah** [comment] 2022-11-20 22:45
Duplicate of #3283

**Closed as not planned** 2022-11-20 22:46 UTC
Labels: duplicate, unable to reproduce, FP Report, maven
