### ISSUE TITLE
False positive on azure-identity 1.1.3

### ISSUE THREAD

**Issue by RobertButtigieg** [dependency-check/DependencyCheck#2912] opened 2020-10-21 04:22 UTC
False positive on the [azure-identity](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity) library.
```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
    <version>1.1.3</version>
</dependency>
```

CPE which is believed to be a FP:
`cpe:2.3:a:keepass:keepass:2.1.4:*:*:*:*:*:*:*`

Other CPEs which are listed as FPs but have already been addressed in issue [#2896](https://github.com/jeremylong/DependencyCheck/issues/2896)
`cpe:2.3:a:http_authentication_library_project:http_authentication_library:1.7.1:*:*:*:*:*:*:*`
`cpe:2.3:a:microsoft:authentication_library:1.7.1:*:*:*:*:*:*:*`
`cpe:2.3:a:openid:openid:7.1.1:*:*:*:*:*:*:*`
`cpe:2.3:a:openid:openid_connect:7.1.1:*:*:*:*:*:*:*`

I am also attaching the report [here](https://github.com/jeremylong/DependencyCheck/files/5413281/azure-identity-1.1.3.zip).

**Comment by jeremylong** [comment] 2020-10-21 11:35
Duplicate of #2896. Until the next release of ODC I would suggest using a local [suppression file](http://jeremylong.github.io/DependencyCheck/general/suppression.html).

**Closed as completed by jeremylong** 2020-10-21 11:35 UTC
Labels: FP Report

**Comment by jeremylong** [comment] 2020-10-21 11:47
Sorry - not enough coffee yet. I thought I had already taken care of keypass...
