### ISSUE TITLE
ODC 8.0.1 - java.lang.NullPointerException

### ISSUE THREAD

**Issue by ortegaantunes** [dependency-check/DependencyCheck#5352] opened 2023-01-19 12:30 UTC
Hi

Since version 7.4.4, we have noticed a `java.lang.NullPointerException` after the "writing report" step. Currently, we are under the 8.0.1 version. Running the debug log I got this:

> DEBUG - Begin deregister driver
2023-01-19 00:51:43,342 org.owasp.dependencycheck.data.nvdcve.DriverLoader:59
DEBUG - End deregister driver
2023-01-19 00:51:43,819 org.owasp.dependencycheck.App:213
ERROR - java.lang.NullPointerException
2023-01-19 00:51:43,819 org.owasp.dependencycheck.App:214
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: java.lang.NullPointerException
	at org.owasp.dependencycheck.analyzer.MSBuildProjectAnalyzer.analyzeDependency(MSBuildProjectAnalyzer.java:174)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.owasp.dependencycheck.data.nuget.XPathMSBuildProjectParser.parse(XPathMSBuildProjectParser.java:71)
	at org.owasp.dependencycheck.analyzer.MSBuildProjectAnalyzer.analyzeDependency(MSBuildProjectAnalyzer.java:120)
	... 7 common frames omitted

![Screenshot 2023-01-19 at 13 29 03](https://user-images.githubusercontent.com/29414973/213443210-c5a5d119-c1b0-4b3b-b5cc-0bbd2e90db51.png)

### Version

![Screenshot 2023-01-19 at 13 26 25](https://user-images.githubusercontent.com/29414973/213442704-72cd8510-6f03-4ab4-8364-0a1abf74ae6d.png)

This was supposed to be fixed on 8.0.0, but for me is still happening.

**Comment by aikebah** [comment] 2023-01-20 23:27
Duplicate of #5144 and the current measure to at least avoid the NPE from happening is not sufficient

**Closed as not planned by aikebah** 2023-01-20 23:27 UTC
Labels: bug, duplicate
