### ISSUE TITLE
Unstable result when scanning JAR with CLI

### ISSUE THREAD

**Issue by kiview** [dependency-check/DependencyCheck#832] opened 2017-08-03 15:38 UTC
We got some unstable results when scanning the same JAR multiple times with the CLI.

We always get:
`cpe:/a:apache:groovy:2.5.0.beta` `org.codehaus.groovy:groovy-all:2.5.0-beta-1`

But we sometimes also get (without any modifications)
`cpe:/a:apache:tomcat:8.5.16 `
`cpe:/a:apache_software_foundation:tomcat:8.5.16`
`cpe:/a:apache_tomcat:apache_tomcat:8.5.16`

In this case the Maven GAV coordinates are also missing (even for the Groovy dependency).

When using the dependencyCheck Gradle plugin it seems we are always getting
`cpe:/a:apache:groovy:2.5.0.beta` `org.codehaus.groovy:groovy-all:2.5.0-beta-1`

The project is using the following dependencies:
```groovy
dependencies {
    final def groovy = 'org.codehaus.groovy:groovy-all:2.5.0-beta-1'

    compile groovy
    toolsCompile groovy

    compile 'io.github.http-builder-ng:http-builder-ng-core:0.17.0'
    compile 'org.apache.commons:commons-text:1.1'
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile "com.moelholm:prometheus-spring-boot-starter:1.0.1"

    testCompile "org.spockframework:spock-core:1.1-groovy-2.4"
    testCompile "org.spockframework:spock-spring:1.1-groovy-2.4"
    testCompile 'com.github.testcontainers:testcontainers-spock:684011c302'
    testCompile('org.springframework.boot:spring-boot-starter-test')

    testRuntime "net.bytebuddy:byte-buddy:1.6.5"
}
```

Any clues why this is happening, or is this even considered normal behavior?

**Comment by kiview** [comment] 2017-08-03 16:04
Oh and I assume, this is because of #684 as well?

**Comment by jeremylong** [comment] 2017-08-05 12:05
I have a sneaking suspicion that this was introduced when the analyzers were parallelized - and the fact that some of them use ArrayLists. This was first reported as issue https://github.com/jeremylong/DependencyCheck/issues/785 - but it was intermittent and we were not able to reproduce the problem. Changes have been made to the [suppression analyzers](https://github.com/jeremylong/DependencyCheck/commit/2753bb97c8f995dc02bddabb2bbc268867ae4176), to ensure the ArrayList is synchronized, that will be included in the next release. However, I need to go investigate other uses of ArrayLists within dependency-check.

**Comment by stefanneuhaus** [comment] 2017-08-07 20:05
For those trying to track down these issues: Do you already have a conjecture which types of analyzers are involved/responsible?

**Comment by jeremylong** [comment] 2017-08-07 22:33
@stefanneuhaus see the above referenced changes to the [suppression analyzers](https://github.com/jeremylong/DependencyCheck/commit/2753bb97c8f995dc02bddabb2bbc268867ae4176). You'll see that previously it used an ArrayList (which is not threadsafe) as a member variable. Later, when the analyzer was using the iterator my best guess (without digging into Java internals) is that  race conditions occur. I fixed the analyzer by synchronizing the use of the ArrayList.  I have not yet looked at other member variables to ensure their thread-safety (likely culprits will be collections).

**Closed as completed** 2017-08-26 10:36 UTC
Labels: bug
