### ISSUE TITLE
Can't run on Azure DevOps on Premises - Windows Server 2016 

### ISSUE THREAD

**Issue by matheusmogi** [dependency-check/DependencyCheck#5819] opened 2023-07-11 09:57 UTC
**Describe the bug**
I'm getting the error when I run any command, even a --version.
'C:\Program' is not recognized as an internal or external command, operable program or batch file.
When I run the same with the same bat in my W11 machine, the version is returned.

**Version of dependency-check used**
The problem occurs using version 8.3.1 of the CLI (or Azure task)

**To Reproduce**
1. Go to the folder that contains the dependency-check.bat
2. Run  .\dependency-check.bat --version
3. See the error

**Expected behavior**
Returns the version and further runs the tool properly

**Comment by aikebah** [comment] 2023-07-12 07:36
Sounds like a duplicate of #5668

**Closed as not planned** 2023-07-12 11:19 UTC
Labels: bug, duplicate
