### ISSUE TITLE
Nexus 3.x does not support XML, only JSON

### ISSUE THREAD

**Issue by b-edwin-bianchi** [dependency-check/DependencyCheck#5833] opened 2023-07-21 17:50 UTC
I am trying to use my internally hosted Nexus server as the central analyzer, as I get intermittent connectivity issues using Maven Central.  The documentation for the tool indicates this feature is supported.  However, in practice it appears to not work with Nexus 3.x.  I am using DependencyCheck version 8.2.1 but it fails on 7.1.2 as well.

Log excerpt:
[2023-07-21T17:34:23.067Z] [DependencyCheck] Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user?s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.
[2023-07-21T17:34:23.067Z] [DependencyCheck] 
[2023-07-21T17:34:23.067Z] [DependencyCheck] 
[2023-07-21T17:34:23.068Z] [DependencyCheck]    About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
[2023-07-21T17:34:23.068Z] [DependencyCheck]    False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html
[2023-07-21T17:34:23.068Z] [DependencyCheck] 
[2023-07-21T17:34:23.068Z] [DependencyCheck] ? Sponsor: https://github.com/sponsors/jeremylong
[2023-07-21T17:34:23.068Z] [DependencyCheck] 
[2023-07-21T17:34:23.068Z] [DependencyCheck] 
[2023-07-21T17:34:23.068Z] [DependencyCheck] [INFO] Analysis Started
[2023-07-21T17:37:00.808Z] [DependencyCheck] [INFO] Finished Archive Analyzer (157 seconds)
[2023-07-21T17:37:01.039Z] [DependencyCheck] [INFO] Finished File Name Analyzer (0 seconds)
[2023-07-21T17:37:09.587Z] [DependencyCheck] [INFO] Finished Jar Analyzer (3 seconds)
[2023-07-21T17:37:28.278Z] [DependencyCheck] [INFO] Finished Central Analyzer (23 seconds)
[2023-07-21T17:37:28.366Z] [DependencyCheck] [WARN] Expected 200 result from Nexus, got 406
[2023-07-21T17:37:28.367Z] [DependencyCheck] [ERROR] Exception occurred initializing Nexus Analyzer.

From our internal Nexus server request.log:
172.30.4.65 - - [21/Jul/2023:13:37:28 -0400] "GET /nexus/service/rest/v1/status HTTP/1.1" 200 - 0 1 "ELB-HealthChecker/2.0" [qtp407875288-509159]
172.30.4.65 - - [21/Jul/2023:13:37:28 -0400] "GET /nexus/service/rest/v1/status HTTP/1.1" 200 - 0 1 "ELB-HealthChecker/2.0" [qtp407875288-514521]
**172.31.9.109 - deployment [21/Jul/2023:13:37:28 -0400] "GET /nexus/service/rest/v1/status HTTP/1.1" 406 - 0 4 "Java/1.8.0_275" [qtp407875288-514383]**
172.30.6.162 - - [21/Jul/2023:13:37:30 -0400] "GET /nexus/service/rest/v1/status HTTP/1.1" 200 - 0 1 "ELB-HealthChecker/2.0" [qtp407875288-514564]
172.30.4.65 - - [21/Jul/2023:13:37:30 -0400] "GET /nexus/service/rest/v1/status HTTP/1.1" 200 - 0 1 "ELB-HealthChecker/2.0" [qtp407875288-514554]

Run tool with the following parameters
--enableNexus 
--nexus http://<NEXUS-INTERNAL-URL>/nexus/service/rest/v1/
--nexusUsesProxy false
--nexusUser <NEXUS-USER>
--nexusPass <NEXUS-PASS>

I have triple checked my Nexus server status endpoint and it returns 200 when hit from a browser or Postman.
http://<NEXUS-INTERNAL-URL>/nexus/service/rest/v1/status in fact returns 200 from Postman.
And you can see in the Nexus server log excerpt above successful calls to the status endpoint from our AWS load balancer.

**Expected behavior**
A 200 OK should return from the status endpoint and my Nexus server should be used as the central analyzer.  Instead I am getting an error 406 from status, which indicates that Nexus does not support the requested XML format.

**Additional context**
I think the problem boils down to the expectation of XML support in Nexus 3, which is apparently not supported in 3:
https://community.sonatype.com/t/api-response-content-type-json-vs-xml/391

If I change this line (link below) in the DependencyCheck source from "application/xml" to "application/json" I get 200 ok from my Nexus status endpoint in the tool.  This allows the preflight check to pass, but of course the rest of the tool execution breaks down and fails as XML is expected downstream:
https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/data/nexus/NexusSearch.java#L183

Please advise.  Thank you.

**Comment by aikebah** [comment] 2023-07-21 20:21
Duplicate of #5319

**Closed as not planned by aikebah** 2023-07-21 20:21 UTC
Labels: bug, duplicate
