### ISSUE TITLE
Getting 403 or 404 exception with NVD API key

### ISSUE THREAD

**Issue by S1Braga** [dependency-check/DependencyCheck#6818] opened 2024-07-08 17:57 UTC
Version 10.0.2

NVD API Key is valid 

delay implementation

.\dependency-check.bat --nvdApiDelay 16000 --updade --nvdApiDelay 6000 --nvdApiKey *****

Error getting 403 or 404

**Comment by chadlwilson** [comment] 2024-07-09 01:37
Please supply proper debug logs and instructions to help reproduce what you're seeing. This is not sufficient and you have not followed the issue template.

**Comment by chadlwilson** [comment] 2024-07-09 01:40
Anyway, it's probably a duplicate of https://github.com/jeremylong/DependencyCheck/issues/6816 (seems something going funny with NVD API keys)

**Comment by S1Braga** [comment] 2024-07-09 01:48
I apologize for the wrong format. Anyway, the key is valid, I did the suggested test

**Comment by chadlwilson** [comment] 2024-07-09 02:04
Okay, but doesn't help us to have duplicate issues so better to close this and subscribe to the other issue.

It may be this is an NVD problem this project can't do anything about, however I can possibly try getting a new key with a different email address to see if they have issues with new keys at the moment?

**Comment by S1Braga** [comment] 2024-07-09 02:08
duplicate of https://github.com/jeremylong/DependencyCheck/issues/6816

**Closed as not planned** 2024-07-09 02:08 UTC
Labels: bug
