### ISSUE TITLE
NVD update fails at 95%

### ISSUE THREAD

**Issue by stevieg27** [dependency-check/DependencyCheck#6530] opened 2024-03-20 21:13 UTC
**Describe the bug**
When I try to update NVD via mvn using even with NVD API Key is failing when it reaches downloading of 95% from yesterday onwards.

**Version of dependency-check used**
maven plugin [9.0.10]

**Log file**
https://gist.github.com/stevieg27/7747caf3af42674b4b4ba6e2337edda5

**To Reproduce**
run mvn org.owasp:dependency-check-maven:update-only along with nvd api key

**Expected behavior**
Proper downloading of all NVD Records

**Comment by chadlwilson** [comment] 2024-03-21 04:06
Effectively dupe of #6531 I think

**Comment by stevieg27** [comment] 2024-03-21 08:19
@chadlwilson This is the same issue.

**Comment by jeremylong** [comment] 2024-03-21 10:15
Even at the high failure rate which I don't have a lot of control over - following either of these should help:

- https://jeremylong.github.io/DependencyCheck/data/cacheh2.html
- https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

I've had the mirror running for a while and haven't seen any real issues: https://github.com/dependency-check/DependencyCheck_Builder/actions/runs/8357974490

**Closed as completed by jeremylong** 2024-03-21 10:15 UTC
Labels: bug
