### ISSUE TITLE
DependancyCheck | Downloading 403 Forbidden

### ISSUE THREAD

**Issue by jkrusic19** [dependency-check/DependencyCheck#2740] opened 2020-07-31 20:39 UTC
**Describe the bug**
When running the Azure DevOps Plugin "Dependancy Check" when it goes to https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2-release.zip I am getting a 403 Forbidden error message. 

**Version of dependency-check used**
5.3.2

**Log file**
Starting Dependency Check...
Creating dependency check test results directory at d:\AgentData\Agent-Azure01\37\TestResults\dependency-check

    Directory: D:\AgentData\Agent-Azure01\37\TestResults

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        7/31/2020   3:18 PM                dependency-check                                                      
Downloading Dependency Check installer...
##[error]System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
Ending Dependency Check...

**To Reproduce**
1. Go to any Windows Server or Powershell Core Terminal (Administrator Mode)
2. Execute => [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 => Ensures outbound connections for invoke-webrequest are going over TLS1.2
3. Execute => Invoke-WebRequest "https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2-release.zip" -OutFile "dependency-check-5.3.2-release.zip"
4. See error => 403 Forbidden.

You can also just go to that URL in your browser and return a 403.

**Expected behavior**
Download file and output to location

**Additional context**

**Comment by jeremylong** [comment] 2020-07-31 21:19
Duplicate of #2740

**Closed as completed by jeremylong** 2020-07-31 21:19 UTC
Labels: bug, duplicate

**Comment by napoleonbenito** [comment] 2020-07-31 21:44
@jeremylong -- not sure if intended, but you marked this ticket as a duplicate of itself.  ;)
I'm wondering if there will be a fix any time soon as this is actually blocking time-sensitive work.  just need to reset expectations if would be a while.

**Comment by jeremylong** [comment] 2020-08-01 10:36
Sorry - duplicate of #2739. This should be resolved.
