### ISSUE TITLE
False Positive on awssdk.netty-nio-client

### ISSUE THREAD

**Issue by amergey** [dependency-check/DependencyCheck#3349] opened 2021-05-03 15:40 UTC
False positive on library software.amazon.awssdk.netty-nio-client - reported as cpe:2.3:a:netty:netty:2.15.17:*:*:*:*:*:*:*
```xml
<!-- https://mvnrepository.com/artifact/software.amazon.awssdk/netty-nio-client -->
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>netty-nio-client</artifactId>
    <version>2.16.52</version>
    <scope>runtime</scope>
</dependency>
```

**Comment by aikebah** [comment] 2021-07-28 23:22
@amergey With which dependency-check invocation do you get this FP? I seem unable to reproduce the results.

**Comment by amergey** [comment] 2021-07-29 08:07
@aikebah with the command line scanning a folder of jars

**Comment by aikebah** [comment] 2021-07-29 08:47
Older version CLI maybe? I just tried DC 6.2.2 release from github scanning a folder with just the awssdk.netty-nio-client and the only identifier I get for the library is `pkg:maven/software.amazon.awssdk/netty-nio-client@2.16.52`. No CPE gets linked.

**Comment by aikebah** [comment] 2021-07-29 09:07
This one appears to be fixed in 6.0.4 by 58dce8d0a33bbc844d1fc7b99eeff3e645f6a1c6

**Comment by aikebah** [comment] 2021-07-29 09:12
This one I would expect to be fixed in 5.2.3 by ec8526d420fe35aa7467535c6922033a905b4b0e

**Comment by amergey** [comment] 2021-07-29 10:03
I still have this reported with 6.2.2, see the report generated after the scan (this is the last in the list among all other false positive I am facing)
[dependency-check-report.txt](https://github.com/jeremylong/DependencyCheck/files/6899668/dependency-check-report.txt)
you can rename the report with html extension, i have set it as txt to attach it

**Comment by aikebah** [comment] 2021-08-04 20:57
Like #3347 this can be attributed to the osgify-ing of Tycho that strips too much metadata to allow for a reliable match

**Closed as completed by aikebah** 2021-08-04 20:57 UTC
Labels: unable to reproduce, FP Report, won't fix
