### ISSUE TITLE
Postgress Error in Version 7.0.0

### ISSUE THREAD

**Issue by hupling** [dependency-check/DependencyCheck#4216] opened 2022-03-17 07:01 UTC
**Describe the bug**
Error with postgress db

Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: ` character varying

**Version of dependency-check used**
The problem occurs using version 7.0.0 of the cli in docker image
**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

```
[ERROR] Database schema does not match this version of dependency-check
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Database schema does not match this version of dependency-check
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.initialize(DatabaseManager.java:217)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.<init>(DatabaseManager.java:123)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:242)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:995)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:868)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:850)
	at org.owasp.dependencycheck.App.runUpdateOnly(App.java:390)
	at org.owasp.dependencycheck.App.run(App.java:166)
	at org.owasp.dependencycheck.App.main(App.java:83)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to check the database schema version
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.ensureSchemaVersion(DatabaseManager.java:505)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.initialize(DatabaseManager.java:214)
	... 8 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: ` character varying
  Hint: No operator matches the given name and argument type. You might need to add an explicit type cast.
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.ensureSchemaVersion(DatabaseManager.java:475)
	... 9 common frames omitted
```

**Expected behavior**
Postgress db is working.

**Additional context**
![grafik](https://user-images.githubusercontent.com/11695964/158754225-386d4173-9eea-4f88-b1b3-9bced086b5d0.png)

https://github.com/jeremylong/DependencyCheck/commit/6c9d4235f4a62b3a69d9b89b2982d00d9509f65c

**Comment by aikebah** [comment] 2022-03-17 08:43
Duplicate of #4124

**Closed as completed by aikebah** 2022-03-17 08:43 UTC
Labels: bug, duplicate
