### ISSUE TITLE
False Positive on various com.google.api.grpc

### ISSUE THREAD

**Issue by amergey** [dependency-check/DependencyCheck#3347] opened 2021-05-03 07:50 UTC
False positive on com.google.api.grpc.proto-google-cloud-kms-v1_0.88.2.jar - reported as cpe:2.3:a:grpc:grpc:0.88.2:*:*:*:*:*:*:*
```xml
<!-- https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-cloud-kms-v1 -->
<dependency>
    <groupId>com.google.api.grpc</groupId>
    <artifactId>proto-google-cloud-kms-v1</artifactId>
    <version>0.88.2</version>
</dependency>
```
False positive on com.google.api.grpc.proto-google-iam-v1_1.0.12.jar - reported as cpe:2.3:a:grpc:grpc:1.0.12:*:*:*:*:*:*:*
```xml
<dependency>
    <groupId>com.google.api.grpc</groupId>
    <artifactId>proto-google-iam-v1</artifactId>
    <version>1.0.12</version>
</dependency>
```
False positive on com.google.api.grpc.proto-google-cloud-secretmanager-v1_1.5.0.jar - reported as cpe:2.3:a:grpc:grpc:1.5.0:*:*:*:*:*:*:*
```xml
<!-- https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-cloud-secretmanager-v1 -->
<dependency>
    <groupId>com.google.api.grpc</groupId>
    <artifactId>proto-google-cloud-secretmanager-v1</artifactId>
    <version>1.5.0</version>
</dependency>

```

**Comment by aikebah** [comment] 2021-07-29 09:03
@amergey Like with #3349 I suspect you're running an older version of DependencyCheck CLI? With version 6.2.2 I cannot reproduce the FPs

**Comment by aikebah** [comment] 2021-07-29 09:08
This one appears to be fixed in 6.0.4 by 58dce8d0a33bbc844d1fc7b99eeff3e645f6a1c6

**Comment by amergey** [comment] 2021-07-29 10:07
still have with 6.2.2, see 2nd to 5th line of the report attached in #3349

**Comment by aikebah** [comment] 2021-07-29 12:09
@amergey Thanks for the report. Based on its content the root-cause appears to be in the source of your jar files.
As an example `pkg:maven/com.google.api.grpc/proto-google-cloud-secretmanager-v1@1.5.0`. For the binary as available on maven central a pom.xml is found which triggers the match , but yours is a different binary as can bee seen from the hashes (and the results in the report):

`28398a491ac9719ce588b250a56680e763c1a840f83d5392e41783c69fe0cebe` <-- Maven Central
`a07a49a4e1d2b7890cce13df3f695f71056e6e8c75bfb1b6a6e52d039e7b47c7` <-- Your report

Maven Central triggers it to be identified with the above package-URL which triggers the reference group/artifact/version based suppression.
Are they self-built jar-files? Or do they come from a different source?

**Comment by amergey** [comment] 2021-07-29 13:34
thanks, you help me to understand what is happening.
We have an eclipse build, based on tycho (it brings eclipse stuff to a maven build), dependencies are declared in a tycho "target-platform" and while downloading from maven tycho osgify jars on the fly when necessary. This is probably the reason.

**Comment by aikebah** [comment] 2021-07-29 15:11
@amergey Sounds like your best option would be a local suppressions file with relatively broad suppressions like

```xml
    <suppress>
        <notes><![CDATA[
        Tycho repackaged Google apis for gRPC are not gRPC itself
        ]]></notes>
        <filePath regex="true">.*lib/com\.google\.api\.grpc.*</filePath>
        <cpe>cpe:/a:grpc:grpc</cpe>
    </suppress>
```

(regex might have errors... tried my best to not make mistakes there, but cannot test its proper matching here)

**Comment by amergey** [comment] 2021-07-29 15:23
yes of course, thanks

**Closed as completed** 2021-08-04 20:56 UTC
Labels: unable to reproduce, FP Report, won't fix
