### ISSUE TITLE
H2 database update extremely slow

### ISSUE THREAD

**Issue by saboacn14** [dependency-check/DependencyCheck#2598] opened 2020-04-17 12:50 UTC
**Describe the bug**
Since (at least) version 5.3.2 the update of a local H2 database is extremely slow. It takes several hours when updating or creating it from scratch. It also seems to be growing very large during the update process (currently >30GB reported by Windows explorer). I only let it completely run through once yesterday evening, which apparently took ~3 hours. Then, the resulting file was back to around 150MB. When switching back to 5.3.0 the whole update process takes about 2-3 minutes.

**Version of dependency-check used**
The problem occurs using version 5.3.2.1 of the gradle plugin 

**Log file**
The two log files for version 5.3.0 and 5.3.2(.1) with debug output. Note that I manually cancelled the 5.3.2.1 task after about 1,5h and omitted repeating log lines by gradle as it was to big for gist to keep all the lines of the file.
https://gist.github.com/saboacn14/9bcd76fa4f83f00808c29e32f522a471
https://gist.github.com/saboacn14/13bf23286d17e873c588f55e266a9e2c

**To Reproduce**
1. Apply dependency-check-gradle version 5.3.2.1 to a simple project and use H2 as database
2. (delete your current database file) 
3. execute the dependencyCheckUpdate gradle task
4. wait for possibly hours
5. (try steps 1-3 with version 5.3.0, should be finished in minutes)

**Expected behavior**
I expect the task to finish in minutes, like with 5.3.0.

**Additional context**
As far as I can see in the task output, the last successful operation was finishing the first ecosystem update step: https://github.com/jeremylong/DependencyCheck/blob/bd6fe1dfa3a1b217d6b70351e24665cb1f71cc1b/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java#L1462

So my guess is that the SQL statement of the second ecosystem step is maybe the issue (since it was added after version 5.3.0): https://github.com/jeremylong/DependencyCheck/blob/bd6fe1dfa3a1b217d6b70351e24665cb1f71cc1b/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java#L1468

I didn't have time to try it with another DB system, so maybe the issue with this query only happens with H2. But the H2 variant becomes rather unusable if the creation/update process always takes multiple hours. 
It is also a bit strange that in this run after manually cancelling the task, the code flow seemed to resume normally. So I'm not sure what is going on during the execution of the database statement. I also didn't have time to let it run for such a long time again, but I can do that next week if needed.

**Comment by jeremylong** [comment] 2020-04-21 10:55
On my system the new update ecosystem does not add hours - maybe 20 seconds or less. However, we have already updated the query and it should improve performance. This will be included in the 5.4.0 release.

**Comment by eyalroth** [comment] 2020-05-05 11:11
I've encountered a similar behavior when upgrading from 5.3.0 to 5.3.2 on my CI build (jenkins). All I can see in the logs (no `--info` or anything) is that the analysis took about 1:20 hours, where it usually takes less than 5 minutes. 

I cannot seem to reproduce this, not on my local machine (Mac) nor on the CI server. And yes, I made sure to delete the H2 database from my `~/.gradle` directory. It might be a case of a nondeterministic behavior which may or may not be related to the H2 database.

**Comment by OrangeDog** [comment] 2020-05-06 10:13
The time taken is not a big issue for me, but the sudden increase in file size is, because it fills the disk and breaks.

The same version of dependency check sometimes updates quickly with no issues, and sometimes hits this issue.

**Comment by ThierryH** [comment] 2020-05-15 14:02
Hello i have the same issue but at a different scale. 
In my case it was a huge version migration from 1.3.3 into 5.3.2. 
The database size has increase from a few hundred MB to 30 GB
ie : 
../.m2/repository/org/owasp/dependency-check-data/4.0# ls -hl
total 29G
drwxr-xr-x   2  4.0K Oct 29  2019 cache
-rw-r--r--   1   48K May 15 13:48 jsrepository.json
-rw-r--r--   1  29G May 15 13:48 odc.mv.db
-rw-r--r--   1     0 May 15 13:48 odc.trace.db
drwxr-xr-x 151 4.0K Oct 29  2019 oss_cache


It's use in a maven build which is failing due to a lack of disk space.

Is it recommanded to rollback to a previous version ( if yes which one ) , or it there a way to restart and to use less disk space ( If the migration of the DB is the cause of the issue , restarting from scratch may help ) ?

Thanks in advance

**Comment by ThierryH** [comment] 2020-05-15 14:18
Solved by : mvn dependency:purge-local-repository -DmanualInclude=org.owasp and rerun the build.
Seems to be an issue with old version of DB,  when restarting from scratch DB size is 128MB  and it took less than 2 min to generate.

**Comment by jeremylong** [comment] 2020-07-11 13:38
Updates will be included in 6.0.0

**Closed as completed** 2020-07-11 13:37 UTC
Labels: bug
