### ISSUE TITLE
2.0.0 not working behind proxy?

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#784] opened 2017-07-04 14:08 UTC
Hi

I have a job to update the database with jenkins, and it is not working since i downloaded version 2.0.0

[DependencyCheck] Performing NVD update only
[DependencyCheck] Unable to update the Dependency-Check database
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.update.exception.UpdateException
[DependencyCheck] Cause: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.utils.DownloadFailedException: Unable to resolve domain 'nvd.nist.gov'
[DependencyCheck] Message: Unable to download the NVD CVE data.
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.NoDataException
[DependencyCheck] Message: No documents exist

With the old version (1.4.5), it works absolutely fine

[DependencyCheck] Performing NVD update only
Finished: SUCCESS

Has anybody reported anything like this? Any suggestion on config changes needed?

Thanks

**Comment by davidkarlsen** [comment] 2017-07-04 21:52
Maybe duplicate of #783 ?

**Comment by javixeneize** [comment] 2017-07-05 08:23
Nop, it also fails with that option disabled. My problem here is it cant connect to nvd.nist.gov

**Comment by jeremylong** [comment] 2017-07-05 10:55
@javixeneize - are you using a proxy?

**Comment by javixeneize** [comment] 2017-07-05 10:56
I am. Its exactly the same proxy i am using in 1.4.5 and it works perfectly
there

Thanks

**Comment by jeremylong** [comment] 2017-07-05 11:01
I actually think this is related to #783. The DNS can't be resolved due to proxy configuration issues. I'm going to track this issue through #783.

**Closed as completed by jeremylong** 2017-07-05 11:01 UTC
Labels: bug, duplicate
