### ISSUE TITLE
Jenkins Plugin "Failed to download https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip from agent"

### ISSUE THREAD

**Issue by Kyyoken** [dependency-check/DependencyCheck#3278] opened 2021-04-12 18:49 UTC
**Describe the bug**
Failed to download https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip from agent

**Version of dependency-check used**
The problem occurs using version 6.1.1 and version 6.1.0 of the jenkins plugin 

**Log file**
`14:30:57  Unpacking https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip to /home/jenkins/agent/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/Default on drmt-api-97391892-6746-4498-86e8-3f1ee0b4d16a-sm50x-k1mwd
14:30:57  ERROR: Failed to download https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip from agent; will retry from master
14:30:57  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-10-0-1-220.ec2.internal/10.0.1.220:39272
14:30:57  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
14:30:57  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
14:30:57  		at hudson.remoting.Channel.call(Channel.java:1001)
14:30:57  		at hudson.FilePath.act(FilePath.java:1158)
14:30:57  		at hudson.FilePath.act(FilePath.java:1147)
14:30:57  		at hudson.FilePath.installIfNecessaryFrom(FilePath.java:1003)
14:30:57  		at hudson.FilePath.installIfNecessaryFrom(FilePath.java:939)
14:30:57  		at hudson.tools.DownloadFromUrlInstaller.performInstallation(DownloadFromUrlInstaller.java:77)
14:30:57  		at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstaller.performInstallation(DependencyCheckInstaller.java:42)
14:30:57  		at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:69)
14:30:57  		at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
14:30:57  		at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:217)
14:30:57  		at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation.forNode(DependencyCheckInstallation.java:66)
14:30:57  		at org.jenkinsci.plugins.DependencyCheck.DependencyCheckToolBuilder.perform(DependencyCheckToolBuilder.java:139)
14:30:57  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
14:30:57  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
14:30:57  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
14:30:57  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:30:57  		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:30:57  		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:30:57  		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:30:57  java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip
14:30:57  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
14:30:57  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
14:30:57  	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
14:30:57  	at java.net.URL.openStream(URL.java:1045)
14:30:57  	at hudson.FilePath$Unpack.invoke(FilePath.java:1037)
14:30:57  	at hudson.FilePath$Unpack.invoke(FilePath.java:1031)
14:30:57  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3314)
14:30:57  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
14:30:57  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
14:30:57  	at hudson.remoting.Request$2.run(Request.java:369)
14:30:57  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
14:30:57  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:30:57  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:30:57  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:30:57  	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:97)
14:30:57  	at java.lang.Thread.run(Thread.java:748)
`

**To Reproduce**
Run dependency-check through the jenkins plugin.

**Expected behavior**
Correctly output dependency-check-report in jenkins pipeline.  (This was working last Friday)

#2843

**Comment by mprins** [comment] 2021-04-13 09:21
Bintray is shutting down soon: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
you were probably hit by a brown-out as a warning

**Comment by jeremylong** [comment] 2021-04-13 10:43
Might be a duplicate of #3251? Also note that the jenkins plugin is still seeking a new maintainer: https://github.com/jenkinsci/dependency-check-plugin#seeking-new-maintainer

**Closed as completed** 2022-01-02 23:02 UTC
Labels: bug, jenkins
