### ISSUE TITLE
False Positive on [library]

### ISSUE THREAD

**Issue by mokel** [dependency-check/DependencyCheck#3901] opened 2021-12-17 15:07 UTC
`netty-tcnative-classes-2.0.46.Final.jar`
is reported as `cpe:2.3:a:netty:netty:2.0.46:*:*:*:*:*:*:*` 

```xml
<suppress>
        <notes><![CDATA[
   file name: netty-tcnative-classes-2.0.46.Final.jar
   ]]></notes>
        <packageUrl regex="true">^pkg:maven/io\.netty/netty\-tcnative\-classes@.*$</packageUrl>
        <cpe>cpe:/a:netty:netty</cpe>
</suppress>
```
Thanks

**Comment by aikebah** [comment] 2021-12-18 23:48
Duplicate of #3889

**Closed as completed by aikebah** 2021-12-18 23:48 UTC
Labels: duplicate, FP Report
