### ISSUE TITLE
[FP]: itext html2pdf 

### ISSUE THREAD

**Issue by freddiN** [dependency-check/DependencyCheck#4251] opened 2022-03-23 15:32 UTC
### Package URl

pkg:maven/com.itextpdf/html2pdf@4.0.1

### CPE

cpe:2.3:a:html2pdf_project:html2pdf:4.0.1:*:*:*:*:*:*:*)

### CVE

CVE 2021-45394

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.0.1

### Description

this is https://github.com/jeremylong/DependencyCheck/issues/4021, but hopefully in a form that gets some attention.

**Comment by aikebah** [comment] 2022-04-04 21:03
closing as duplicate of 4021, handling it there

**Closed as completed by aikebah** 2022-04-04 21:03 UTC
Labels: duplicate, FP Report
