### ISSUE TITLE
Postgres database error

### ISSUE THREAD

**Issue by irrandon** [dependency-check/DependencyCheck#3414] opened 2021-06-02 09:02 UTC
**Describe the bug**
Database connection errors if scanning a large amount of artifacts with activated postgres backend. (In our case over 200 jars)
There is also a large time gap of an hour between line 18 and 20 of the log file.

**Version of dependency-check used**
Docker 6.2.0 with postgres 11.10.0

**Log file**
[Link](https://gist.github.com/irrandon/0ef90682e363c18f0e56527fdfaab260)

**To Reproduce**
Just scan a large amount of artifacts with a postgres database.

**Expected behavior**
No database errors.

**Additional context**
Works fine with version 6.1.6

**Comment by jeremylong** [comment] 2021-06-10 10:40
duplicate of #3408. This should be resolved with 6.2.2 (currently being released)./

**Closed as completed by jeremylong** 2021-06-10 10:40 UTC
Labels: bug, duplicate
