### ISSUE TITLE
Add support for scanning of libraries written in C

### ISSUE THREAD

**Issue by shahdhruvin** [dependency-check/DependencyCheck#281] opened 2015-07-16 06:29 UTC
On a linux appliance, there are many 3rd party libraries getting used which are written in C (.so files)
For example: 
Libtiff, Groff are written in C, and often gets listed with multiple CVEs.
This enhancement will make this tool even more powerful.

**Comment by hansjoachim** [comment] 2015-07-16 16:01
Thanks for reporting.

This sounds like related or possibly duplicate of #208.

**Comment by shahdhruvin** [comment] 2015-07-16 17:14
This surely looks like a duplicate.
I wonder why this didn't show up when I searched for list of enhancements.

Anyways, you can mark and close it as duplicate, or let me know if I am
required to do that.

Thanks for the prompt response.
This dependency-check toll is really useful and we are integrating it in
our CI system one product after another!
- Dhruvin

**Comment by jeremylong** [comment] 2015-07-17 12:14
Thanks for the feedback. Because of how dependency-check works I don't think we'll be able to scan a file system containing DLLs or SOs and expect to get any reasonable results. However, some work has gone into scanning C build files.

**Closed as completed by jeremylong** 2015-07-17 12:14 UTC
Labels: duplicate
