### ISSUE TITLE
Missing or empty dependency-check.html (aggregate goal)

### ISSUE THREAD

**Issue by marcelstoer** [dependency-check/DependencyCheck#386] opened 2015-10-15 06:32 UTC
This is related to #325 and possibly to #189 as well. With #189 fixed I thought I'd give 1.3.1 a try but in more cases than not I don't see a valid `dependency-check.html`. I'm wondering if it's simply a user mistake...

I have a multi-module project and all tests / modifications were done in Maven root.
## Command line

`mvn org.owasp:dependency-check-maven:1.3.1:aggregate -DlogFile=./dependency-check.log -q` works ok. I get a valid `target/dependency-check.html`.
## Running during build

With the above working fine I "Mavenized" the command by adding the following to a profile in the `pom.xml`:

``` xml
<build>
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>1.3.1</version>
  <executions>
    <execution>
      <goals>
        <goal>aggregate</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

This doesn't work, it produces `target/dependency-check.ser` but no HTML file.
## Running during site build

Next I added it to the site build like so:

``` xml
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>1.3.1</version>
  <reportSets>
    <reportSet>
      <reports>
        <report>aggregate</report>
      </reports>
    </reportSet>
  </reportSets>
</plugin>
```

When I run `mvn site` I get a 0KB `target/site/dependency-check.html` but  `target/dependency-check.ser` seems sufficiently big (6.2KB).

**Comment by jeremylong** [comment] 2015-10-16 10:06
The aggregate goal has known issues with anything beyond `site:site` (i.e. stage, deploy). We have a plan to resolve this issue - but it will require running the plugin twice. However, you appear to be having issues with just `site:site`.

Can you provide the `mvn -v` and the output of `mvn site -X`?

**Comment by jeremylong** [comment] 2015-10-16 10:27
I just had another thought on why the aggregate goal may be failing for some people. Is there any chance one or more of the modules are skipped during the build (specifically, the last module in the reactor)?

```
[INFO] Reactor Summary:
[INFO]
[INFO] parent1 ............................................ SUCCESS [ 21.041 s]
[INFO] project1 ........................................... SUCCESS [  8.034 s]
[INFO] project2 ........................................... SUCCESS [  9.684 s]
[INFO] project3 ........................................... SKIPPED
```

**Comment by marcelstoer** [comment] 2015-10-16 11:29
> Can you provide the `mvn -v`

```
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T15:51:42+02:00)
Maven home: /Applications/ApacheGroup/Maven-3.2.2
Java version: 1.8.0_11, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"
```

> and the output of `mvn site -X`

That'd be 56M of information I can't disclose, sorry. However, I can confirm that none of the ~40 modules was skipped. If you tell me what to look for in the debug output I can maybe report that back in a somewhat anonymized form.

I also tried with Maven 3.3.3 but the result is the same. Every module and the root project have a `/target/dependency-check.ser`.

**Comment by jeremylong** [comment] 2015-10-18 10:27
If you used the `check` goal you get valid HTML reports in all of the projects - correct? Completely understand that is not ideal when dealing with 40+ modules, just want to confirm there isn't something else going on.

**Comment by marcelstoer** [comment] 2015-10-20 05:21
I just confirmed, yes, the `check` goal produces valid HTML reports.

**Comment by jeremylong** [comment] 2015-10-20 09:46
Thanks for the information.  I am still not entirely sure why it is failing on your installation. Let me describe exactly how the aggregate goal works (currently) and this may give you a clue. 

As dependency-check requires the maven perform dependency resolution it only works on a module after the compile phase. As such, the aggregate goal runs the equivelent of the check goal on each child module, when it gets to the last child it will then cycle through all the results of the previous results to build the dependency-check aggregate report. This results in the following:
1. When the parent pom is processed maven generates a blank dependency-check report
2. Each child project will have a valid .ser file; this is the serialized data to build the dependency-check report.
3. If the last module is skipped, the blank aggregate report will not be over-written by the correct aggregate report.
4. If a plugin is moving the site results, such as `site:stage`, then when the parent pom is processed a blank dependency-check report is generated and then moved to the staging directory. Once the last child module is processed the correct dependency-check aggregate report is written to the original site directory - but has not been moved to the staging directory.

From your earlier comments I don't think item 4 is causing the issue in your case, but I could be mistaken. I will be reaching out to the maven developer list to see if I am missing something or if they can suggest a different approach.

I have also been considering making the aggregate goal a report-only goal that does not actually run dependency-check. Instead it would entirely rely upon the serialized data file. The downside of this is that you would have to run maven twice to generate the aggregate goal.

**Comment by jeremylong** [comment] 2016-02-24 01:37
I may have just figured out what the problem is - are any of the modules configured to skip the Maven site? Example:

``` xml
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>

       <maven.site.skip>true</maven.site.skip>

    </properties>
```

**Comment by jeremylong** [comment] 2016-02-24 01:44
I believe this issue has been resolved in the 1.3.5-SNAPSHOT. The patch will be included in the next release. However, issue #325 is still present and will likely have issues for anything beyond site:site (i.e. site:stage or site:deploy may result in blank reports being staged or deployed).

**Comment by marcelstoer** [comment] 2016-02-24 05:58
> are any of the modules configured to skip the Maven site?

No.

**Comment by jeremylong** [comment] 2016-02-25 00:05
well, that is unfortunate... At least I solved one reason that the report was not being generated...

**Comment by hohwille** [comment] 2016-04-28 22:32
I am facing the same problem. As my problem is about an open-source project this could help you to trace down the issue:
https://github.com/oasp/oasp4j/issues/401
I therefore I created this PR that is not yet accepted
https://github.com/oasp/oasp4j/pull/404
So to reproduce clone this and generate site:
https://github.com/hohwille/oasp4j

**Comment by hohwille** [comment] 2016-04-28 22:33
BTW (off topic): You might also like the idea of that open-source project called OASP as it cares a lot about OWASP. See here:
https://github.com/oasp/oasp4j/wiki/guide-security

**Comment by jeremylong** [comment] 2016-08-20 16:21
The aggregation code has been completely re-written in 1.4.3-SNAPSHOT. The fix will be released with the next release.

**Closed as completed by jeremylong** 2016-08-20 16:21 UTC
