### ISSUE TITLE
Ant task can't open dependencycheck.properties after update to 6.1.1

### ISSUE THREAD

**Issue by dr0ps** [dependency-check/DependencyCheck#3169] opened 2021-03-01 16:41 UTC
**Describe the bug**
I can run 6.1.0 without problem but as soon as I upgrade to 6.1.1 the ant task fails with this output:

dependencycheck:
[dependency-check] Unable to create an Input Stream for dependencycheck.properties
[dependency-check] Did not find settings file 'dependencycheck.properties'.

It can then not load a database driver and fails. I tried to read through the changes that went into 6.1.1. but I found no obvious candidate. Also this problem not only appears on my machine but also on our Jenkins server so it probably is not specific to by setup.

**Version of dependency-check used**
The problem occurs using version 6.1.1 of the ant task

This happens on OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.10)

**Comment by jeremylong** [comment] 2021-03-02 11:12
Duplicate of #3146. A fix is included in 6.1.2.

**Closed as completed by jeremylong** 2021-03-02 11:12 UTC
Labels: bug, duplicate
