### ISSUE TITLE
False Positive on netty-tcnative-classes

### ISSUE THREAD

**Issue by seandmccarthy** [dependency-check/DependencyCheck#3889] opened 2021-12-15 22:34 UTC
False positive on library netty-tcnative-classes-2.0.46.Final.jar - reported as  cpe:/:netty:netty:2.0.46

```xml
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative</artifactId>
    <version>2.0.46.Final</version>
</dependency>
```

**Comment by sebastianrothe** [comment] 2021-12-15 23:17
Duplicate of  #3865

**Closed as completed** 2021-12-19 10:25 UTC
Labels: FP Report
