### ISSUE TITLE
muteJCS() seems not to work and prints heaps of stack traces 

### ISSUE THREAD

**Issue by cbollmeyer** [dependency-check/DependencyCheck#2150] opened 2019-08-14 10:47 UTC
**Describe the bug**

Since upgrading to 5.2.1 (from 5.0.0), building Maven projects with the dependency plugin enabled leads to verbose exception stack traces printed. AdoptOpenJDK 11.02+9 here, build running under Eclipse 06-2019 with integrated M2E 1.12.0. Everything worked perfectly before (just updated the version number), now the output is cluttered with stack traces because of a `NoSuchFieldException` as the root cause. 

** Version of dependency-check used **
5.2.1

Configuration:

      <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>5.2.1</version>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

** Log file **

Sorry, can only provide the log output from the console window atm. For sake of brevity, the sample is for `AbstractDiskCache` and `AbstractMemoryCache` only, but similar output seems to be generated for most | each of the libraries in the list though, making the output _quite_ more verbose than before :-) 

`[INFO] --- dependency-check-maven:5.2.1:check (default) @ lwc-core-master ---
[WARNING] Failed to reset the log level of org.apache.commons.jcs.auxiliary.disk.AbstractDiskCache, it will continue being noisy.
java.lang.NoSuchFieldException: currentLogLevel
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.muteJCS(BaseDependencyCheckMojo.java:1821)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:1399)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:802)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[WARNING] Failed to reset the log level of org.apache.commons.jcs.engine.memory.AbstractMemoryCache, it will continue being noisy.
java.lang.NoSuchFieldException: currentLogLevel
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
`

(...)

**To Reproduce**

Build a Maven JAR project under JDK11 with the 5.2.1 plugin enabled. 

**Expected behavior**

It would help if the plugin could just print a simple failure message in case of a `NoSuchFieldException`, omitting the entire stack trace output which clutters everything.

**Additional context**

These issues appear on multiple machines and projects around here with all similar results. The build itself completes successfully.

HTH & thanks for the hard work,
-- Ch.

**Comment by jeremylong** [comment] 2019-08-16 12:32
This has been reported previously - one solution is to upgrade your version of Maven. We will continue to look into this; but I would recommend upgrading.

**Comment by cbollmeyer** [comment] 2019-08-16 12:56
Hm. I would, but Eclipse 06-2019 is using the embedded Maven release which is 3.6.1 already. At least it says so under Maven | Installations. I did not configure any other Maven releases there and only have a local 3.6.0 exclusively used for generating the encrypted Nexus credentials, but that's not used in the local builds.

**Comment by jeremylong** [comment] 2019-08-17 12:20
I love issues that I can't reproduce - "works on my machine"(tm)... The only other time this was reported it was on an older version of Maven and upgrading resolved the issue. I personally avoid Eclipse at all cost - so there might be something going on there.

However, I just looked at the code and realized what one of the issues is - the log statement in muteJCS() should not have been at the warn level.

**Comment by Flugtiger** [comment] 2019-09-20 06:22
I can reproduce this problem with dependency-check 5.2.1, Eclipse 19-09 and Maven 3.6.1 (embedded into Eclipse). If I build with Maven 3.5.3 there is no problem, so i suppose 'muteJCS' only works with Maven 3.5.x.

**Comment by jeremylong** [comment] 2019-09-20 12:21
I apologize - the fix for this has been in code, we just haven't completed a release due to other priorities.  We will try and push a release shortly.

**Closed as completed** 2019-09-22 21:30 UTC
Labels: bug
