### ISSUE TITLE
Trouble downloading database with 2.0.0

### ISSUE THREAD

**Issue by davidkarlsen** [dependency-check/DependencyCheck#783] opened 2017-07-04 13:45 UTC
I have trouble downloading the database after upgrading to 2.0.0, 1.4.5 with same config worked fine.
I've been experimenting turning the "central analyzer" on|off (AFAIK 1.4.x used the nexus analyzer) - but I am unsure about the differences between the two analyzers.

gist of log:
https://gist.github.com/0c5331a86988c51d9ff40d1ad3e83f3f

**Comment by jeremylong** [comment] 2017-07-05 11:03
I found the issue - in the 2.0.0 upgrade we updated the updater to use more concurrency. There is a nuance to how the global `Settings` object works. When I merged the PR I missed that this was done incorrectly. The end result is that default settings are used when downloading the NVD/CVE data. As you are behind a proxy - the download fails.

I should have an update released tonight.

**Comment by javixeneize** [comment] 2017-07-05 11:17
That was quick! Thank you very much Jeremy

**Comment by javixeneize** [comment] 2017-07-06 15:43
Hi

Will a new 2.0.1 version be released for the Jenkins plugin or it will just a fix on the existing version?

**Comment by stevespringett** [comment] 2017-07-06 15:50
Jenkins plugin releases are synchronized with the core dependency-check releases. Whenever Jeremy releases a new version of the core, I release a new version of the Jenkins plugin with that core.

**Comment by jeremylong** [comment] 2017-07-08 09:44
@javixeneize can you confirm that the proxy issue you were facing has been resolved in 2.0.1?

**Comment by javixeneize** [comment] 2017-07-08 09:51
Hi. Yes, its solved, but i had other issues yesterday that might be related
to my proxy. The db was not fully downloaded and the pipeline was marked as
success. Will let you know on monday

Am i the official tester of dependency check? ;) happy to help to improve
the tool

**Comment by jeremylong** [comment] 2017-07-08 11:14
lol... yeah, sorry about the bug in 2.0.0 - I need to setup a virtual lab with a proxy to fully test this out in the future.

Thanks!

**Closed as completed by jeremylong** 2017-07-08 11:14 UTC
Labels: bug

**Comment by davidkarlsen** [comment] 2017-07-09 21:10
@jeremylong Maybe you could do use of https://github.com/takari/takari-plugin-testing-project for integration-testing of the maven plugin?

**Comment by jeremylong** [comment] 2017-07-13 19:12
@davidjahn I'm using the [Maven Invoker Plugin](https://maven.apache.org/plugins/maven-invoker-plugin/) for integration testing of the maven plugin. The issue is I would need to setup an environment with a proxy to fully test this and I have not done that (yet).
