### ISSUE TITLE
mvn site site:stage -- staging has empty dependency-check-report.html

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#325] opened 2015-08-27 07:47 UTC
I noticed that the `aggregate` goal does not work for a multi-module project with the `site:stage` goal.
The `dependency-check-report.html` file exists, but is 0 bytes.

Note that `mvn site` works -- the problem is unique to `site:stage`.

**Comment by jeremylong** [comment] 2015-08-28 10:11
Thank you for pointing this out. I have been able to replicate the issue on my side - now I just have to figure out why....

**Comment by jeremylong** [comment] 2015-09-05 10:42
The good news is I've figured out why this happens - the bad news, I haven't come up with a solution yet. I'm likely going to have to email the maven dev list. A basic description of the problem is that the dependencies must be resolved in order for dependency-check-maven to work. The order of execution for a generic multi-module pom would be:
1. parent
2. module1
3. module2

Because `parent` runs before the child modules the dependencies of the child modules are not resolved at the time the parent is executing. As such, when `dependency-check-maven:aggregate` is executing against `parent` there is no (easy/obvious) way to know what the dependencies of the children are. The aggregate goal works for `mvn site` because it cheats - for each module it will execute and create a serialized data file containing the information on the dependencies; however, a blank HTML report is written. When maven gets to the last project in the build the aggregate goal will go back and re-write all of the HTML reports based off of this serialized data. 

The problem is `site:stage` executes on each of the projects in order - so the blank html report gets copied instead of waiting until the last project and then copying the correct html report. 

--Jeremy

**Comment by awhitford** [comment] 2016-01-16 18:46
Has there been any recent traction/research on this?
I'm a little puzzled by this problem; I'm trying to think about how other plugins solve this.

**Comment by jeremylong** [comment] 2016-01-17 13:05
The real issue comes down to dependency resolution. I haven't found another reporting plugin with an aggregation goal that requires dependency-resolution.

When the parent runs the aggregation goal the child modules have not undergone dependency resolution. I can't find an easy api to kick off dependency-resolution. Thus, the only thing I have come up with is to require a second run to actually make the aggregate goal work. I.e. the first run we produce the serialized data files and the second run an aggregate goal could read these files. So you would do something like this:

``` shell
$ mvn verify
$ mvn site site:stage
```

This is of course assuming that the check goal is configured in the build and that the aggregate goal is configured in the reportingg section.

**Comment by erik-wramner** [comment] 2016-02-24 15:50
We are also quite interested in getting this fixed. I can see the problem, it seems more logical to run the parent goal last but that's not how it works.

**Comment by jeremylong** [comment] 2016-02-24 17:10
Right.  The only solution I've been able to come up with would require
running maven twice.

If no one can suggest any other ideas I will likely implement this soon.

-jeremy

**Comment by awhitford** [comment] 2016-03-12 19:07
I am wondering if a [lifecycle extension](http://maven.apache.org/examples/maven-3-lifecycle-extensions.html) would help.

**Comment by jeremylong** [comment] 2016-03-12 19:56
The issue is that all of the lifecycles run on the parent before going to
the next project. Thus, unless you run Maven twice we don't have all
dependencies on all child projects (first run we can create the serialized
dependency-check data, second run for reporting we can read it in and
create the report).

--Jeremy

**Comment by colezlaw** [comment] 2016-03-12 20:37
It's been a long, long time since I wrote a Maven plugin from scratch, but
IIRC, you can add an annotation for a mojo to get access to the reactor
order. If this project is the last one in the reactor, it could read the
serialized data from all the child projects, then write the report to the
root of the reactor. Yes - it's a kludge.

**Comment by jeremylong** [comment] 2016-08-20 16:18
The aggregation code has been completely re-written in 1.4.3-SNAPSHOT. The fix will be released with the next release.

**Closed as completed by jeremylong** 2016-08-20 16:18 UTC
Labels: bug
