### ISSUE TITLE
False Positive on kotlin-stdlib-1.4.30.jar

### ISSUE THREAD

**Issue by dingo15** [dependency-check/DependencyCheck#3227] opened 2021-03-25 15:19 UTC
False positive on library kotlin-stdlib-1.4.30.jar - reported as cpe:2.3:a:jetbrains:kotlin:1.4.0:milestone1::::::
```xml
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.4.30</version>
</dependency>

```

**Comment by aikebah** [comment] 2021-04-07 11:43
What version of DependencyCheck do you use? Cannot reproduce it with Maven Plugin / DC 6.1.5

**Comment by aikebah** [comment] 2021-04-07 12:19
Manage to reproduce with gradle plugin

**Comment by aikebah** [comment] 2021-04-07 12:39
Is essentially a duplicate of #3133, follow up for fix in there

**Closed as completed by aikebah** 2021-04-07 12:39 UTC
Labels: duplicate, FP Report
