### ISSUE TITLE
MissingMethodException when running dependencyCheckAggregate via Gradle after upgrading from 7.4.4 to 8.0.0

### ISSUE THREAD

**Issue by torland-klev** [dependency-check/DependencyCheck#5329] opened 2023-01-17 08:32 UTC
**Describe the bug**
Running `gradle dependencyCheckAggregate` in a multi-module project results in the following error
> Execution failed for task ':dependencyCheckAggregate'.
> No signature of method: static org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.convertIdentifier() is applicable for argument types: (org.gradle.api.internal.artifacts.DefaultProjectComponentIdentifier) values: [project :(first module in project)]

You'll find the accompanying stack-trace below.

Both `dependencyCheckUpdate` and `dependencyCheckAnalyze` works flawlessly.

**Version of dependency-check used**
Using org.owasp:dependency-check-gradle:8.0.0
Running on Gradle 7.5.1

**Log file**
[Stacktrace](https://gist.github.com/torland-klev/118714a5bad0f2e26fd440e8481f5be8)

**To Reproduce**
1. Run `gradle dependencyCheckAggregate`
2. Observe error

**Expected behavior**
Dependecy check should initialize and run

**Additional context**
N/A

**Comment by aikebah** [comment] 2023-01-17 22:14
duplicate of #5306

**Closed as not planned by aikebah** 2023-01-17 22:14 UTC
Labels: bug, duplicate
