### ISSUE TITLE
[Feature Request] Dependency Status Tab on Azure Dev Ops

### ISSUE THREAD

**Issue by gsantopaolo** [dependency-check/DependencyCheck#2182] opened 2019-09-04 14:05 UTC
Hi there,
   i'm using DependencyCheck on Azure DevOps and it seems a quite powerful tool, compliment for that.
I've installed the extension and configured the Dependecy, and everything is working fine, I can download test results from artifacts, I've also configured a Publish Dependency Check Test Results Task so i got i nice view of the tests result.

It would be nice to add a Dependency Status Tab where to show the report directly in Azure Dev Ops in addition to download it as artifact

All the best.

**Comment by aikebah** [comment] 2019-09-07 17:48
@gsantopaolo I didn't know about this Azure Devops extension, but a bit of googling led me to https://github.com/dependency-check/azuredevops

That looks like the spot to file your Feature Request. The Azure DevOps integration (a wrapper around the CLI tool of this project) is not managed by this DependencyCheck project, but appears to be managed in that azuredevops dependency-check github project.

The merging of PRs by @ejohn20 matches with the contributors mentioned at the [marketplace](https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck&ssr=false#overview) as well as the comments in its Q&A section where an issue in that github project is referenced.

**Comment by ejohn20** [comment] 2019-09-11 05:41
This is a duplicate of this issue: https://github.com/dependency-check/azuredevops/issues/3

**Comment by jeremylong** [comment] 2019-09-11 12:35
Closing this issue as it will be handled in the azuredevops repo.

**Closed as completed by jeremylong** 2019-09-11 12:35 UTC
Labels: duplicate, question
