### ISSUE TITLE
NVD API REQUEST ISSUE

### ISSUE THREAD

**Issue by HauruShiro** [dependency-check/DependencyCheck#7193] opened 2024-11-26 12:17 UTC
**Describe the bug**

This isn’t the first time I’ve encountered this bug; usually, I would update, and the issue would disappear.  
But today, nothing seems to work...

Here’s what I’m getting:  

```
[WARNING] NVD API request failures are occurring; retrying request for the 8th time  
[WARNING] Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=68000: 3rd time  
[INFO] Downloaded 50,000/271,508 (18%)  
```

I’d like to understand the mechanism behind all this. Is it because the URL is no longer accessible?  

I’m completely lost.  

**Version of dependency-check used**
The problem occurs using version X.X.X of the ____ (cli, gradle plugin, maven plugin, etc.)

--> 10.0.3

**To Reproduce**

mvn org.owasp:dependency-check-maven:10.0.3:aggregate -DskipSystemScope=true -DassemblyAnalyzerEnabled=false -DnodeAuditAnalyzerEnabled=true -DnodeAnalyzerEnabled=true -DnugetconfAnalyzerEnabled=false -DnuspecAnalyzerEnabled=false -Dformat=XML -DfailOnError=false -DnvdApiKey=APIKEY

**Comment by h4ckerfr0st** [comment] 2024-11-26 13:44
I am having the same problem in my side, I generated new keys and did not work


[WARN] Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=104000 : 3 time
[WARN] NVD API request failures are occurring; retrying request for the 9 time
[WARN] Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=94000 : 3 time
[WARN] NVD API request failures are occurring; retrying request for the 5 time
[WARN] NVD API request failures are occurring; retrying request for the 5 time
[WARN] NVD API request failures are occurring; retrying request for the 5 time
[WARN] NVD API request failures are occurring; retrying request for the 6 time
[WARN] NVD API request failures are occurring; retrying request for the 5 time

**Comment by ivopogace** [comment] 2024-11-26 13:46
Same
Retrying request /rest/json/cves/2.0?lastModStartDate=xxxxxxxx&lastModEndDate=xxxxxxx&resultsPerPage=2000&startIndex=2000 : 3 time
NVD API request failures are occurring; retrying request for the 5 time
NVD API request failures are occurring; retrying request for the 6 time
NVD API request failures are occurring; retrying request for the 5 time

Version: 11.1.0

**Comment by h4ckerfr0st** [comment] 2024-11-26 13:51
Apparently there was similarities in the issue reported above here:
https://github.com/jeremylong/DependencyCheck/issues/6758

The only fix was to use local database that you might previously had used --noupdate  option in the cli so it uses its local cache

     - dependency-check --disableNodeAudit --disablePnpmAudit  --noupdate  --scan . --disableAssembly --enableExperimental -s . -o build --format XML --project "$PROJECT_ID" --exclude ".git/**" --exclude ".venv/**" --exclude "**/__pycache__/**" --exclude ".tox/**" --nvdApiKey "*******************"
 unlike my case where my runners are dynamic no space to run local db 




[UPDATE]

https://www.nist.gov/itl/nvd

![Screenshot from 2024-11-26 10-56-52](https://github.com/user-attachments/assets/3ab3cf9e-3268-4430-9a11-dc69f0d792be)

**Comment by HauruShiro** [comment] 2024-11-26 14:15
@h4ckerfr0st 

Thanks for your reply! The goal wasn’t to use a local database, but it might be a fix.
I think I’ll use a local database in the future to avoid this kind of issue.


and thx for the UPDATE BTW

**Comment by h4ckerfr0st** [comment] 2024-11-26 14:18
No problem, thanks for letting me know.

**Comment by nhumblot** [comment] 2024-11-26 15:45
Duplicate of #7178, closing.

**Closed as completed by nhumblot** 2024-11-26 15:45 UTC
Labels: bug
