### ISSUE TITLE
Why am I suddenly encountering this for Dependency Check? [WARN] Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=120000 : 2 time

### ISSUE THREAD

**Issue by shana2x** [dependency-check/DependencyCheck#7186] opened 2024-11-24 12:21 UTC
I have been using the OWASP Dependency check version 10 but now I am encountering this issue: _[WARN] Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=120000 : 2 time_. I thought I needed to update to the latest version which is as of now the dependency-check-11.1.0., Still I am encountering the issue, and I am not sure why is that or where is the issue. Please help find and solve this. Thanks!
![Screenshot 2024-11-24 202028](https://github.com/user-attachments/assets/ef8db3ef-1b00-4827-8862-3937742e4a85)

**Comment by jeremylong** [comment] 2024-11-24 12:29
load at the NVD side. Nothing we can do about it other then be good users and keep a copy of the database between executions so we don't download the full NVD data set every time it is run.

**Comment by marcelstoer** [comment] 2024-11-25 08:55
A duplicate of #7178 (and many others). Please close it.

**Comment by nhumblot** [comment] 2024-11-26 07:47
Closing as duplicate of #7178

**Closed as completed by nhumblot** 2024-11-26 07:47 UTC
Labels: question
