### ISSUE TITLE
Error from GrokAssembly:

### ISSUE THREAD

**Issue by McMlok** [dependency-check/DependencyCheck#3071] opened 2021-01-11 15:25 UTC
Hello,

May I ask what is the right place for GrokAssembly.zip in dependency-check cli? When I run dependency-check.bat in my .NET project I see warning "Error from GrokAssembly: null". I downloaded the GrokAssembly repository build and publish it and finally made a zip file. I placed zip into plugin folder in cli but still I see warning. I tried many places but with same result. 

CLI Command:  dependency-check.bat --proxyserver localhost --proxyport 3128 --scan . --log run.log
OS: Windows 10 1909
OWASP Dependency checker: 6.04
.NET Core: Both 2.X and 3.X installed.

Thank you

**Comment by jeremylong** [comment] 2021-01-12 11:55
You can ignore the warning. The issue is due to a typo:
 
```diff
-                if (Strings.isNullOrEmpty(errorOutput)) {
+                if (!Strings.isNullOrEmpty(errorOutput)) {
                     LOGGER.warn("Error from GrokAssembly: {}", errorOutput);
```

The fix will be included in the next release.

**Closed as completed by jeremylong** 2021-01-12 11:55 UTC
Labels: bug
