### ISSUE TITLE
regression: dependency-check-maven does not take dependencies' repositories into account anymore

### ISSUE THREAD

**Issue by victornoel** [dependency-check/DependencyCheck#3626] opened 2021-09-03 12:21 UTC
I upgraded the maven plugin from 6.2.2 to 6.3.1 and now I'm getting this error during the execution of the check goal:
```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	ArtifactResolverException: Could not find artifact com.github.graphstream:gs-ui-swing:jar:2.0 in central (https://repo.maven.apache.org/maven2)
		caused by ArtifactResolutionException: Could not find artifact com.github.graphstream:gs-ui-swing:jar:2.0 in central (https://repo.maven.apache.org/maven2)
		caused by ArtifactNotFoundException: Could not find artifact com.github.graphstream:gs-ui-swing:jar:2.0 in central (https://repo.maven.apache.org/maven2)
	ArtifactResolverException: Could not find artifact com.github.graphstream:gs-core:jar:2.0 in central (https://repo.maven.apache.org/maven2)
		caused by ArtifactResolutionException: Could not find artifact com.github.graphstream:gs-core:jar:2.0 in central (https://repo.maven.apache.org/maven2)
		caused by ArtifactNotFoundException: Could not find artifact com.github.graphstream:gs-core:jar:2.0 in central (https://repo.maven.apache.org/maven2)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectMavenDependencies (BaseDependencyCheckMojo.java:1320)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectDependencies (BaseDependencyCheckMojo.java:1437)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts (BaseDependencyCheckMojo.java:1098)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts (BaseDependencyCheckMojo.java:1064)
    at org.owasp.dependencycheck.maven.CheckMojo.scanDependencies (CheckMojo.java:104)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1689)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:950)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
...
```

What is particular with this dependency is that it is downloaded from a repository that is declared in the pom of one of my project's dependency:
- my project -> another project -> gs-core
- with "another project" declaring a repository in its pom where gs-core can be found

Also note that executing the check goal directly on "another project" works as expected.

**Comment by aikebah** [comment] 2021-09-03 20:13
@victornoel As a side-note, why not use the [officially published](https://graphstream-project.org/doc/Install/) artifacts from graphstream from Maven Central [https://repo1.maven.org/maven2/org/graphstream/](https://repo1.maven.org/maven2/org/graphstream/)? 

I'll see if I can reproduce your issue locally as I've seen they're published under unofficial coordinates that your project also uses in the SciJava public repository

**Comment by tjj225** [comment] 2021-09-03 20:20
I have a similar ArtifactResolverException after upgrade from 6.2.2 to 6.3.1. The jar is a third party jar not in any public repos.

The report gets generated, but it is a build failure. Ideally, this could be a warning in the report.

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.3.1:check (default-cli) on project springBootApp: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:

**Comment by aikebah** [comment] 2021-09-03 21:23
Able to reproduce locally with a similar structure as @victornoel, so I'll investigate its root cause and will try to come up with a fix

**Comment by aikebah** [comment] 2021-09-03 22:11
Root cause lies in Maven dependency-tree shared library upgrade from 3.0.1 to 3.1.0 ef665ed8ebb6f351ed54a4b75d58986b211a9c18, reverting the library back to 3.0.1 makes resolution function properly

**Comment by aikebah** [comment] 2021-09-03 22:34
@jeremylong I'll look into a structural fix, if you would like to do a quick-fix you could release a new minor with that dependabot-PR reverted.

**Comment by aikebah** [comment] 2021-09-04 18:04
Likely to stem from [MSHARED-519](https://issues.apache.org/jira/browse/MSHARED-519) which might explain why we now run into #1751 again (allthough the artifacts were resolved before, from the correct repository they're not marked resolved in the nodes of the DependencyGraphBuilder, so we try to resolve them and run into the issue that the repository configuration inside the child poms is not taken into account).

Will need some further investigation to find out what would be the proper way to get the resolved artifacts available.

**Comment by aikebah** [comment] 2021-09-04 21:51
@jeremylong Running a final testrun on a working patch... no need for an interim-fix PR expected to follow soon

**Comment by victornoel** [comment] 2021-09-05 09:23
> As a side-note, why not use the officially published artifacts from graphstream from Maven Central https://repo1.maven.org/maven2/org/graphstream/?

Hehe, very good question, I think it's because initially those weren't available on Maven Central yet but only on jitpack, thank you for the info!

In any case, thx for investigating it and finding a clean solution :)

**Closed as completed** 2021-09-07 12:44 UTC
Labels: bug

**Comment by jeremylong** [comment] 2021-09-07 12:46
@aikebah thanks for the research and PR! I'll try to push a new release soon!
