### ISSUE TITLE
Add username&password to the hostedSuppressions

### ISSUE THREAD

**Issue by yonyes** [dependency-check/DependencyCheck#5569] opened 2023-03-20 16:46 UTC
**Is your feature request related to a problem? Please describe.**
With the latest versions of the Gradle plugin (8+), it attempts to retrieve data from https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml. Without storing its certificate on our machine, we are unable to access this site directly. Sadly, its certificate is updated almost every day, and we cannot do this process on every machine every day, so we are stuck. 

The file above can be added to our internal _Artifactory_ every day. By using `hostedSuppressions`, everyone will be able to access it. However, in our _Artifactory_, there are usernames and API tokens/passwords, and the current `hostedSuppressions` configuration doesn't provide anything besides the URL.  

**Describe the solution you'd like**
Add username and API token/password to the `hostedSuppressions`.

**Describe alternatives you've considered**
I don't have any.

**Additional context**
In the case that you try to run the plugin without making any changes, you will receive these errors (which is indicative of a missing certificate):
```
Error downloading file https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml; unable to connect.
.
.
.
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
.
.
.
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 .
.
.
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
 

In the case that you try to run the plugin with our _Artifactory_ URL, 
```
    analyzers {
        hostedSuppressions {
            url = "https://*****.jfrog.io/artifactory/******/owasp/publishedSuppressions.xml"
        }
        assemblyEnabled = false
    }
```

you will receive these errors (which is indicative of a missing username&password):
`Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error retrieving https://*****.jfrog.io/artifactory/******/owasp/publishedSuppressions.xml; received response code 401; null`

**Comment by aikebah** [comment] 2023-03-22 08:20
Duplicate of #5387

**Closed as not planned by aikebah** 2023-03-22 08:20 UTC
Labels: duplicate, enhancement
