### ISSUE TITLE
Invalid cross-device link (DependencyCheck v3.3.0)

### ISSUE THREAD

**Issue by freecode1973** [dependency-check/DependencyCheck#1404] opened 2018-07-27 08:22 UTC
I tried to switch to newest dependency-check-maven plugin, which results in following error:

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.3.0:update-only (owasp-dependency-update) on project jenkins-maintenance: An exception occurred while downloading updates. Please see the log file for more details. Failed to initialize the RetireJS repo: /tmp/dctempfe32b35b-0b68-41f7-b514-c7c417e4b4fb/jsrepository.json -> /var/local/share/owasp-cache-3.3.0/jsrepository.json: Invalid cross-device link -> [Help 1]

* Directory /tmp is located on a fast, local hard disk (SSD). 
* /var/local/share is in this case an NFS share. I also tried to use local workspace for cve database directory or inside maven repository but same error occures. (With database I mean the directory set by dataDirectory property. Deleting this directory will not help)
* System is a RedHat linux, with Jenkins as build system

The problem does not occur if database and temporary directory are located on same hard disc partition. 

Is it possible to use soft links instead of hard links ? Alternatively...how to overwrite the temporary directory used by dependency-check-maven plugin, without affecting other maven modules (so I could set it to same disk where database is stored).

**Comment by jeremylong** [comment] 2018-07-27 10:45
Thanks, this is a duplicate of #1394 - although I had originally thought this was a windows only bug.  A fix will be published with the next release.

The only way to change the temp directory for a maven build would be to set the `temp.directory` system variable:
```
mvn -Dtemp.directory=/path/to/tmp verify
```

**Closed as completed** 2018-08-06 12:51 UTC
Labels: bug, duplicate
