### ISSUE TITLE
NullpointerException caused by dependency version string

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#3220] opened 2021-03-24 07:52 UTC
**Describe the bug**
I get the following exception when analyzing my project with `mvn dependency-check:aggregate`:

> java.lang.NullPointerException
    at java.lang.String.endsWith (String.java:1485)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.lambda$null$3 (CPEAnalyzer.java:380)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:176)
    at java.util.HashMap$KeySpliterator.forEachRemaining (HashMap.java:1603)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.lambda$addMajorVersionToTerms$5 (CPEAnalyzer.java:383)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:177)
    at java.util.HashMap$EntrySpliterator.forEachRemaining (HashMap.java:1746)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.addMajorVersionToTerms (CPEAnalyzer.java:378)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE (CPEAnalyzer.java:279)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency (CPEAnalyzer.java:764)
    at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze (AbstractAnalyzer.java:131)
    at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:88)
    at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:37)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)

By playing around with this issue I found out, that this exception does not occur when I change the version of a depenency of my project. The version string causing the problem is `3.0-v1.0-RC2-SNAPSHOT`. If I change it to say `3.0-v1.0-RC1` the analysis finishes successfully without the exception being thrown.

**Version of dependency-check used**
The problem occurs using version 6.1.3 of the maven plugin.

**Log file**
https://gist.github.com/raafael911/bd21a8beab7b218189c11f2358ddd538

**To Reproduce**
1. Add a depenency with the version (or similar) `3.0-v1.0-RC2-SNAPSHOT` to your project
2. Run dependency-check:aggregate
3. See error

**Expected behavior**
I would expect that the version string `3.0-v1.0-RC2-SNAPSHOT` in a dependency to not cause an exception and the analysis to finish successfully.

If I can provide any additional information or help you in any way please let me know.

Cheers

**Comment by jeremylong** [comment] 2021-03-24 09:59
duplicate of #3212

**Closed as completed by jeremylong** 2021-03-24 09:59 UTC
Labels: bug, duplicate
