### ISSUE TITLE
Add 'ArtifactoryAnalyzer' or allow 'CentralAnalyzer' to use a different URL

### ISSUE THREAD

**Issue by glianeric** [dependency-check/DependencyCheck#756] opened 2017-06-05 20:44 UTC
Hello,

  I would like to use my in-house Artifactory server instead of Central for running the analysis.   I believe that the NexusAnalyzer calls a specific nexus API to do its work.

  Artifactory provides a REST API with json responses, so this implementation would require reading in:
* User name
* User password
* OR API token

It would call the REST APIs for searches:
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-SEARCHES

There are also APIs for downloading the POMs if that is desired - I haven't looked deep enough into the centralAnalyzer to understand it yet.

**Comment by stevespringett** [comment] 2017-06-05 21:00
This should be implemented as a dedicated ArtifactoryAnalyzer so that Artifactory, Nexus, and Central can be queried independently.

**Comment by jeremylong** [comment] 2017-06-06 21:56
See enhancement request #60. The issue is that the checksum search would be required for an ArtifactoryAnalyzer to work for the Jenkins, CLI, and ANT implementations of ThreadFix.  The checksum search is only available in the pro edition.

**Comment by glianeric** [comment] 2017-06-07 13:56
I have responded on that issue but I shall do so here as well:  I have AF PRO and I am willing to test this.  It would be great if you were able to add ... I guess 'ArtifactoryProAnalyzer' :) to dependency-check.
Please let me know what your decision is.  I can also put in a request with jfrog to add checksum search to the OSS version though I don't know if they'd be willing to do this.

**Comment by jeremylong** [comment] 2017-06-09 10:33
I'm going to close this issue in favor of the original #60.

**Closed as completed by jeremylong** 2017-06-09 10:33 UTC
Labels: duplicate, enhancement
