### ISSUE TITLE
[FP]: netty-tcnative-boringssl-static is matching the chromium project

### ISSUE THREAD

**Issue by jrmcdonald** [dependency-check/DependencyCheck#4776] opened 2022-08-24 09:21 UTC
### Package URl

pkg:maven/io.netty/netty-tcnative-boringssl-static@2.0.54.Final

### CPE

cpe:2.3:a:chromium_project:chromium:2.0.54:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.1.1

**Comment by tisonkun** [comment] 2022-08-25 11:20
This can be a duplicate of https://github.com/jeremylong/DependencyCheck/issues/4154

**Comment by aikebah** [comment] 2022-11-20 17:10
Released, but issue wasn't triggered to be closed by the merge, in 7.3.1/7.3.2

**Closed as completed by aikebah** 2022-11-20 17:10 UTC
Labels: FP Report, maven
