### ISSUE TITLE
6.3.1 -> 6.3.2 NPE

### ISSUE THREAD

**Issue by jasonparallel** [dependency-check/DependencyCheck#3694] opened 2021-10-04 13:43 UTC
Updating the maven plugin from 6.3.1 to 6.3.2 is yielding the following NPE

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal [32morg.owasp:dependency-check-maven:6.3.2:check[m [1m(default-cli)[m on project [m: [1;31mExecution default-cli of goal org.owasp:dependency-check-maven:6.3.2:check failed.[m
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.owasp:dependency-check-maven:6.3.2:check failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.shared.artifact.filter.resolve.transform.EclipseAetherFilterTransformer$2.accept(EclipseAetherFilterTransformer.java:152)
	at org.eclipse.aether.util.filter.AndDependencyFilter.accept(AndDependencyFilter.java:83)
	at org.eclipse.aether.util.filter.OrDependencyFilter.accept(OrDependencyFilter.java:81)
	at org.eclipse.aether.util.graph.visitor.FilteringDependencyVisitor.visitEnter(FilteringDependencyVisitor.java:80)
	at org.eclipse.aether.util.graph.visitor.TreeDependencyVisitor.visitEnter(TreeDependencyVisitor.java:67)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:343)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:332)
	at org.apache.maven.shared.transfer.dependencies.resolve.internal.Maven31DependencyResolver.resolveDependencies(Maven31DependencyResolver.java:216)
	at org.apache.maven.shared.transfer.dependencies.resolve.internal.Maven31DependencyResolver.resolveDependencies(Maven31DependencyResolver.java:198)
	at org.apache.maven.shared.transfer.dependencies.resolve.internal.DefaultDependencyResolver.resolveDependencies(DefaultDependencyResolver.java:60)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectMavenDependencies(BaseDependencyCheckMojo.java:1328)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectDependencies(BaseDependencyCheckMojo.java:1467)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts(BaseDependencyCheckMojo.java:1114)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts(BaseDependencyCheckMojo.java:1080)
	at org.owasp.dependencycheck.maven.CheckMojo.scanDependencies(CheckMojo.java:104)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:1719)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:966)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 21 more
```

**Comment by tim-tk** [comment] 2021-10-04 14:04
I have the same problem, but only for 1 out of 3 projects, all configured the same...

**Comment by jbaltus** [comment] 2021-10-05 06:55
Same issue for our projects ...

**Comment by jeremylong** [comment] 2021-10-05 12:44
duplicate of https://github.com/jeremylong/DependencyCheck/issues/3679.  I'm hoping @aikebah or myself can get to this soon.

**Closed as completed by jeremylong** 2021-10-05 12:44 UTC
Labels: bug, duplicate
