### ISSUE TITLE
If an analyser is disabled due to missing executable then it should not check for the analyzer report

### ISSUE THREAD

**Issue by savornicesei** [dependency-check/DependencyCheck#4008] opened 2022-01-20 13:22 UTC
Hi all,

**Describe the bug**
I am running dep-check on a react web application.

Acording to the [documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html), I could use Yarn and pnpm analyzers if I provide the path to `yarn` and `pnpm`.

If they are not disabled and no paths are provided, the tool displays a warning that the 2 analysers will be disabled but at the end it's looking for the reports generated by those analyzers and errors because the reports do not exist.

![image](https://user-images.githubusercontent.com/917232/150335946-9b719a26-4d46-4e4d-99be-fd9dc5e6f2ee.png)

In v6.5.3, if I add `--disableYarnAudit` and `--disablePnpmAudit` I get:
`[DependencyCheck] Unrecognized option: --disablePnpmAudit`

I'm using the following command line arguments from Jenkins:
```bash
--project "SomeProject frontend"
--scan "${WORKSPACE}"
--out "${WORKSPACE}\reports"
--data "c:\Programe\owasp\data"
--format XML
--format HTML
--format JSON
--disablePyDist
--disablePyPkg
--disableMSBuild
--disableRubygems
--disableBundleAudit
--disableCocoapodsAnalyzer
--disableSwiftPackageManagerAnalyzer
--disableSwiftPackageResolvedAnalyzer 	
--disableAutoconf
--disableOpenSSL
--disableCmake
--disableArchive
--disableJar
--disableComposer
--disableCpan
--disableOssIndex
--disableNuspec
--disableNugetconf
--disableAssembly
--disableGolangDep
--disableGolangMod
```

**Expected behaviour**
I would expect that if the external tools are not provided, the analysis and report generator should skip them. Or at least promote the warnings to errors and stop analysis right there.

**Version of dependency-check used**
6.5.3

**Log file**
Reached 2Gb in size so it's not fit for gist.

Thank you.

**Comment by js-writer** [comment] 2022-01-21 13:07
I can confirm.
When I try to add flag --disablePnpmAudit to my pipeline I get this error:
`Unrecognized option: --disablePnpmAudit`
And then the list of available options is shown.
So there must be a bug in code because for example: disableYarnAudit is working.

**Comment by jeremylong** [comment] 2022-02-07 11:19
Fixed with https://github.com/jeremylong/DependencyCheck/pull/4037.

**Closed as completed by jeremylong** 2022-02-07 11:19 UTC
Labels: bug
